#!/usr/bin/env python3
"""Module to generate predictions using a trained Keras model."""

import tensorflow.keras as K


def predict(network, data, verbose=False):
    """Generate predictions for the input data using a Keras model.

    Args:
        network (K.Model): The trained Keras model to use for prediction.
        data (numpy.ndarray or tf.Tensor): The input data to make predictions
            on.
        verbose (bool, optional): Whether to print progress logs during
            prediction. Defaults to False.

    Returns:
        numpy.ndarray: The prediction output generated by the model.
    """
    return network.predict(data, verbose=verbose)
